ckpt_path: msanii.pt
output_dir: samples/audio2audio
batch_size: 4
num_frames: 8387584
duration: null
output_audio_format: wav
seed: 0
device: cuda
dtype: float32
num_inference_steps: 200
verbose: false
use_neural_vocoder: true
num_griffin_lim_iters: 200
_kwargs_: {}
data_dir: audio_data_dir
num_workers: 4
pin_memory: false
strength: 1.0
