ckpt_path: msanii.pt
output_dir: samples/inpainting
batch_size: 4
num_frames: 8387584
duration: null
output_audio_format: wav
seed: 0
device: cuda
dtype: float32
num_inference_steps: 200
verbose: false
use_neural_vocoder: true
num_griffin_lim_iters: 200
_kwargs_: {}
data_dir: audio_data_dir
num_workers: 4
pin_memory: false
masks:
- 3-5,6-7,20-100
eta: 0.0
jump_length: 10
jump_n_sample: 10
